# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(751, 631)
        Form.setMinimumSize(QtCore.QSize(751, 631))
        Form.setMaximumSize(QtCore.QSize(751, 631))
        self.board = QtWidgets.QWidget(Form)
        self.board.setGeometry(QtCore.QRect(0, 0, 751, 631))
        self.board.setStyleSheet("font: 10pt \"微软雅黑\";    \n"
"color: #333333;\n"
"border-radius: 15px;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(222, 228, 246, 220), stop: 1 rgba(236, 217, 226, 220));\n"
"")
        self.board.setObjectName("board")
        self.widget_button = QtWidgets.QWidget(self.board)
        self.widget_button.setGeometry(QtCore.QRect(70, 560, 611, 41))
        self.widget_button.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(230, 178, 194, 240), stop: 1 rgba(189, 202, 232, 240));\n"
"}")
        self.widget_button.setObjectName("widget_button")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_button)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_blog = QtWidgets.QPushButton(self.widget_button)
        self.button_blog.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_blog.setFont(font)
        self.button_blog.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_blog.setObjectName("button_blog")
        self.verticalLayout_3.addWidget(self.button_blog)
        self.title_bar = QtWidgets.QWidget(self.board)
        self.title_bar.setGeometry(QtCore.QRect(0, 0, 751, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_bar.sizePolicy().hasHeightForWidth())
        self.title_bar.setSizePolicy(sizePolicy)
        self.title_bar.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-radius: 15px;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgb(225, 182, 196), stop: 1 rgb(181, 205, 238));\n"
"")
        self.title_bar.setObjectName("title_bar")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.hboxlayout.setContentsMargins(15, 0, 15, 0)
        self.hboxlayout.setSpacing(15)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_title = QtWidgets.QLabel(self.title_bar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(200 ,200, 200,0);\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label_title.setObjectName("label_title")
        self.hboxlayout.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.button_min = QtWidgets.QPushButton(self.title_bar)
        self.button_min.setMinimumSize(QtCore.QSize(16, 16))
        self.button_min.setMaximumSize(QtCore.QSize(16, 16))
        self.button_min.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 190, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(0, 170, 255);\n"
"}")
        self.button_min.setText("")
        self.button_min.setObjectName("button_min")
        self.hboxlayout.addWidget(self.button_min)
        self.button_exit = QtWidgets.QPushButton(self.title_bar)
        self.button_exit.setMinimumSize(QtCore.QSize(16, 16))
        self.button_exit.setMaximumSize(QtCore.QSize(16, 16))
        self.button_exit.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 60, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 170, 255);\n"
"}")
        self.button_exit.setText("")
        self.button_exit.setObjectName("button_exit")
        self.hboxlayout.addWidget(self.button_exit)
        self.textBrowser = QtWidgets.QTextBrowser(self.board)
        self.textBrowser.setGeometry(QtCore.QRect(10, 70, 731, 461))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    padding: 5px;\n"
"}\n"
"QTextBrowser::verticalScrollBar {\n"
"    width: 10px;\n"
"    background-color: #ddd;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QTextBrowser::verticalScrollBar::handle {\n"
"    background-color: #999;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QTextBrowser::verticalScrollBar::add-line,\n"
"QTextBrowser::verticalScrollBar::sub-line {\n"
"    width: 0px; /* 隐藏上下箭头按钮 */\n"
"}")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_blog.setText(_translate("Form", "去踩一踩我的主页  (｡•̀ᴗ-)✧"))
        self.label_title.setText(_translate("Form", "关于"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:11pt; font-weight:600;\">关于作者</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">开发者：ichinoseyuu </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">联系方式：1915914448@qq.com</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">作者是华北水利水电大学24届毕业生，本项目为作者的毕业设计</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'微软雅黑\'; font-size:10pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:11pt; font-weight:600;\">关于软件</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">软件名称：交通标识检测助手</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">版本：v1.0b</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">版权信息：版权所有 © 2024 ichinoseyuu 保留所有权利</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">使用条款：本程序仅用于学习和个人用途，不得用于商业目的.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">隐私政策：本程序不会收集任何用户数据，所有的图像数据均在本地进行处理,，不会传输到任何服务器或第三方服务商.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">帮助和支持：如果您在使用本程序时遇到任何问题或需要帮助，请联系作者.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">免责声明：本程序基于深度学习技术，使用的是yolox算法，作者从github上clone的模型，花费大量时间进行进行优化和改进，虽经过精心设计和测试，但识别仍存在误差较大，对于因使用本程序造成的任何损失或损害，作者概不负责.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:10pt;\">特别鸣谢：感谢github大佬bubbliiiing对此训练模型的无私分享.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
