# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1181, 931)
        MainWindow.setMinimumSize(QtCore.QSize(1181, 931))
        MainWindow.setMaximumSize(QtCore.QSize(1181, 931))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    rgb(255, 255, 255)\n"
"    border-radius: 15px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.board = QtWidgets.QWidget(self.centralwidget)
        self.board.setGeometry(QtCore.QRect(0, 0, 1181, 931))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.board.sizePolicy().hasHeightForWidth())
        self.board.setSizePolicy(sizePolicy)
        self.board.setStyleSheet("font: 11pt \"微软雅黑\";    \n"
"color: #333333;\n"
"border-radius: 15px;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(222, 228, 246, 240), stop: 1 rgba(236, 217, 226, 240));\n"
"")
        self.board.setObjectName("board")
        self.widget_button_1 = QtWidgets.QWidget(self.board)
        self.widget_button_1.setGeometry(QtCore.QRect(1000, 50, 161, 241))
        self.widget_button_1.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(230, 178, 194, 240), stop: 1 rgba(189, 202, 232, 240));\n"
"}")
        self.widget_button_1.setObjectName("widget_button_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_button_1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_pic = QtWidgets.QPushButton(self.widget_button_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pic.sizePolicy().hasHeightForWidth())
        self.button_pic.setSizePolicy(sizePolicy)
        self.button_pic.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_pic.setObjectName("button_pic")
        self.verticalLayout.addWidget(self.button_pic)
        self.button_files = QtWidgets.QPushButton(self.widget_button_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_files.sizePolicy().hasHeightForWidth())
        self.button_files.setSizePolicy(sizePolicy)
        self.button_files.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_files.setObjectName("button_files")
        self.verticalLayout.addWidget(self.button_files)
        self.button_heatmap = QtWidgets.QPushButton(self.widget_button_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_heatmap.sizePolicy().hasHeightForWidth())
        self.button_heatmap.setSizePolicy(sizePolicy)
        self.button_heatmap.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_heatmap.setObjectName("button_heatmap")
        self.verticalLayout.addWidget(self.button_heatmap)
        self.button_video = QtWidgets.QPushButton(self.widget_button_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_video.sizePolicy().hasHeightForWidth())
        self.button_video.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_video.setFont(font)
        self.button_video.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_video.setObjectName("button_video")
        self.verticalLayout.addWidget(self.button_video)
        self.button_realtime = QtWidgets.QPushButton(self.widget_button_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_realtime.sizePolicy().hasHeightForWidth())
        self.button_realtime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_realtime.setFont(font)
        self.button_realtime.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_realtime.setObjectName("button_realtime")
        self.verticalLayout.addWidget(self.button_realtime)
        self.widget_button_2 = QtWidgets.QWidget(self.board)
        self.widget_button_2.setGeometry(QtCore.QRect(1000, 310, 161, 311))
        self.widget_button_2.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(230, 178, 194, 240), stop: 1 rgba(189, 202, 232, 240));\n"
"}")
        self.widget_button_2.setObjectName("widget_button_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_button_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_select_file = QtWidgets.QPushButton(self.widget_button_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_select_file.sizePolicy().hasHeightForWidth())
        self.button_select_file.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_select_file.setFont(font)
        self.button_select_file.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_select_file.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_select_file.setObjectName("button_select_file")
        self.verticalLayout_2.addWidget(self.button_select_file)
        self.button_handle = QtWidgets.QPushButton(self.widget_button_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_handle.sizePolicy().hasHeightForWidth())
        self.button_handle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_handle.setFont(font)
        self.button_handle.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_handle.setObjectName("button_handle")
        self.verticalLayout_2.addWidget(self.button_handle)
        self.button_stop = QtWidgets.QPushButton(self.widget_button_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stop.sizePolicy().hasHeightForWidth())
        self.button_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_stop.setFont(font)
        self.button_stop.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_stop.setObjectName("button_stop")
        self.verticalLayout_2.addWidget(self.button_stop)
        self.button_confirm = QtWidgets.QPushButton(self.widget_button_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_confirm.sizePolicy().hasHeightForWidth())
        self.button_confirm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_confirm.setFont(font)
        self.button_confirm.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_confirm.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_confirm.setObjectName("button_confirm")
        self.verticalLayout_2.addWidget(self.button_confirm)
        self.button_display_result = QtWidgets.QPushButton(self.widget_button_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_display_result.sizePolicy().hasHeightForWidth())
        self.button_display_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_display_result.setFont(font)
        self.button_display_result.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_display_result.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_display_result.setObjectName("button_display_result")
        self.verticalLayout_2.addWidget(self.button_display_result)
        self.button_display_result_2 = QtWidgets.QPushButton(self.widget_button_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_display_result_2.sizePolicy().hasHeightForWidth())
        self.button_display_result_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_display_result_2.setFont(font)
        self.button_display_result_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_display_result_2.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_display_result_2.setObjectName("button_display_result_2")
        self.verticalLayout_2.addWidget(self.button_display_result_2)
        self.widget_button_3 = QtWidgets.QWidget(self.board)
        self.widget_button_3.setGeometry(QtCore.QRect(1000, 810, 161, 101))
        self.widget_button_3.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(230, 178, 194, 240), stop: 1 rgba(189, 202, 232, 240));\n"
"}")
        self.widget_button_3.setObjectName("widget_button_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_button_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_about = QtWidgets.QPushButton(self.widget_button_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_about.sizePolicy().hasHeightForWidth())
        self.button_about.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_about.setFont(font)
        self.button_about.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_about.setObjectName("button_about")
        self.verticalLayout_3.addWidget(self.button_about)
        self.button_exit_2 = QtWidgets.QPushButton(self.widget_button_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_exit_2.sizePolicy().hasHeightForWidth())
        self.button_exit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_exit_2.setFont(font)
        self.button_exit_2.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(170, 170, 255, 180), stop: 1 rgba(0, 255, 255, 180));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(0, 170, 255, 180), stop: 1 rgba(170, 170, 255, 180));\n"
"}")
        self.button_exit_2.setObjectName("button_exit_2")
        self.verticalLayout_3.addWidget(self.button_exit_2)
        self.label_display_window = QtWidgets.QLabel(self.board)
        self.label_display_window.setGeometry(QtCore.QRect(20, 340, 960, 540))
        self.label_display_window.setMinimumSize(QtCore.QSize(960, 540))
        self.label_display_window.setMaximumSize(QtCore.QSize(960, 540))
        self.label_display_window.setStyleSheet("QLabel{    \n"
"    border: 1px solid rgb(193, 202, 231);\n"
"     border-radius: 0px;\n"
"    /*background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(232, 224, 234, 240), stop: 1 rgba(225, 229, 244,240));*/\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_display_window.setWordWrap(True)
        self.label_display_window.setObjectName("label_display_window")
        self.widget_message_2 = QtWidgets.QWidget(self.board)
        self.widget_message_2.setGeometry(QtCore.QRect(180, 310, 801, 31))
        self.widget_message_2.setStyleSheet("QWidget{\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border: 1px solid rgb(193, 202, 231);\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(232, 224, 234, 240), stop: 1 rgba(225, 229, 244,240));\n"
"}")
        self.widget_message_2.setObjectName("widget_message_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_message_2)
        self.verticalLayout_8.setContentsMargins(2, 0, 15, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_message = QtWidgets.QLabel(self.widget_message_2)
        self.label_message.setMinimumSize(QtCore.QSize(0, 25))
        self.label_message.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_message.setStyleSheet("QLabel{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")
        self.verticalLayout_8.addWidget(self.label_message)
        self.widget_message_1 = QtWidgets.QWidget(self.board)
        self.widget_message_1.setGeometry(QtCore.QRect(20, 310, 161, 31))
        self.widget_message_1.setStyleSheet("QWidget{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(230, 178, 194, 240), stop: 1 rgba(189, 202, 232, 240));\n"
"}")
        self.widget_message_1.setObjectName("widget_message_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_message_1)
        self.verticalLayout_7.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_message_title = QtWidgets.QLabel(self.widget_message_1)
        self.label_message_title.setMinimumSize(QtCore.QSize(120, 20))
        self.label_message_title.setMaximumSize(QtCore.QSize(120, 20))
        self.label_message_title.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_message_title.setObjectName("label_message_title")
        self.verticalLayout_7.addWidget(self.label_message_title)
        self.widget_display_1 = QtWidgets.QWidget(self.board)
        self.widget_display_1.setGeometry(QtCore.QRect(20, 880, 91, 31))
        self.widget_display_1.setStyleSheet("QWidget{\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(230, 178, 194, 240), stop: 1 rgba(189, 202, 232, 240));\n"
"}")
        self.widget_display_1.setObjectName("widget_display_1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_display_1)
        self.verticalLayout_9.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_display_title = QtWidgets.QLabel(self.widget_display_1)
        self.label_display_title.setMinimumSize(QtCore.QSize(110, 20))
        self.label_display_title.setMaximumSize(QtCore.QSize(110, 20))
        self.label_display_title.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_display_title.setObjectName("label_display_title")
        self.verticalLayout_9.addWidget(self.label_display_title)
        self.widget_display_2 = QtWidgets.QWidget(self.board)
        self.widget_display_2.setGeometry(QtCore.QRect(110, 880, 871, 31))
        self.widget_display_2.setStyleSheet("QWidget{\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border: 1px solid rgb(193, 202, 231);\n"
"    border-top: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(232, 224, 234, 240), stop: 1 rgba(225, 229, 244,240));\n"
"}")
        self.widget_display_2.setObjectName("widget_display_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_display_2)
        self.horizontalLayout_5.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_display_path_2 = QtWidgets.QLabel(self.widget_display_2)
        self.label_display_path_2.setMinimumSize(QtCore.QSize(70, 20))
        self.label_display_path_2.setMaximumSize(QtCore.QSize(70, 20))
        self.label_display_path_2.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"}")
        self.label_display_path_2.setObjectName("label_display_path_2")
        self.horizontalLayout_5.addWidget(self.label_display_path_2)
        self.label_display_path = QtWidgets.QLabel(self.widget_display_2)
        self.label_display_path.setMinimumSize(QtCore.QSize(0, 25))
        self.label_display_path.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_display_path.setStyleSheet("QLabel{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_display_path.setText("")
        self.label_display_path.setTextFormat(QtCore.Qt.AutoText)
        self.label_display_path.setObjectName("label_display_path")
        self.horizontalLayout_5.addWidget(self.label_display_path)
        self.widget_path_3 = QtWidgets.QWidget(self.board)
        self.widget_path_3.setGeometry(QtCore.QRect(20, 50, 961, 241))
        self.widget_path_3.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_path_3.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(230, 178, 194, 240), stop: 1 rgba(189, 202, 232, 240));\n"
"}")
        self.widget_path_3.setObjectName("widget_path_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_path_3)
        self.gridLayout.setContentsMargins(15, 9, 15, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.label_01 = QtWidgets.QLabel(self.widget_path_3)
        self.label_01.setMinimumSize(QtCore.QSize(150, 25))
        self.label_01.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_01.setFont(font)
        self.label_01.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_01.setObjectName("label_01")
        self.gridLayout.addWidget(self.label_01, 0, 0, 1, 1)
        self.label_06 = QtWidgets.QLabel(self.widget_path_3)
        self.label_06.setMinimumSize(QtCore.QSize(150, 25))
        self.label_06.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_06.setFont(font)
        self.label_06.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_06.setObjectName("label_06")
        self.gridLayout.addWidget(self.label_06, 8, 0, 1, 1)
        self.label_02 = QtWidgets.QLabel(self.widget_path_3)
        self.label_02.setMinimumSize(QtCore.QSize(150, 25))
        self.label_02.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_02.setFont(font)
        self.label_02.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_02.setObjectName("label_02")
        self.gridLayout.addWidget(self.label_02, 1, 0, 1, 1)
        self.label_03 = QtWidgets.QLabel(self.widget_path_3)
        self.label_03.setMinimumSize(QtCore.QSize(150, 25))
        self.label_03.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_03.setFont(font)
        self.label_03.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_03.setObjectName("label_03")
        self.gridLayout.addWidget(self.label_03, 2, 0, 1, 1)
        self.label_07 = QtWidgets.QLabel(self.widget_path_3)
        self.label_07.setMinimumSize(QtCore.QSize(150, 25))
        self.label_07.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_07.setFont(font)
        self.label_07.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_07.setObjectName("label_07")
        self.gridLayout.addWidget(self.label_07, 9, 0, 1, 1)
        self.label_mode = QtWidgets.QLabel(self.widget_path_3)
        self.label_mode.setMinimumSize(QtCore.QSize(0, 25))
        self.label_mode.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_mode.setStyleSheet("QLabel{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_mode.setText("")
        self.label_mode.setObjectName("label_mode")
        self.gridLayout.addWidget(self.label_mode, 0, 1, 1, 1)
        self.lineEdit_file_out = QtWidgets.QLineEdit(self.widget_path_3)
        self.lineEdit_file_out.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_file_out.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_file_out.setFont(font)
        self.lineEdit_file_out.setStyleSheet("QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.lineEdit_file_out.setText("")
        self.lineEdit_file_out.setObjectName("lineEdit_file_out")
        self.gridLayout.addWidget(self.lineEdit_file_out, 9, 1, 1, 1)
        self.label_05 = QtWidgets.QLabel(self.widget_path_3)
        self.label_05.setMinimumSize(QtCore.QSize(150, 25))
        self.label_05.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_05.setFont(font)
        self.label_05.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_05.setObjectName("label_05")
        self.gridLayout.addWidget(self.label_05, 7, 0, 1, 1)
        self.label_08 = QtWidgets.QLabel(self.widget_path_3)
        self.label_08.setMinimumSize(QtCore.QSize(150, 25))
        self.label_08.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_08.setFont(font)
        self.label_08.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_08.setObjectName("label_08")
        self.gridLayout.addWidget(self.label_08, 10, 0, 1, 1)
        self.label_04 = QtWidgets.QLabel(self.widget_path_3)
        self.label_04.setMinimumSize(QtCore.QSize(150, 25))
        self.label_04.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_04.setFont(font)
        self.label_04.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_04.setObjectName("label_04")
        self.gridLayout.addWidget(self.label_04, 11, 0, 1, 1)
        self.label_currentPath = QtWidgets.QLabel(self.widget_path_3)
        self.label_currentPath.setMinimumSize(QtCore.QSize(0, 25))
        self.label_currentPath.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_currentPath.setStyleSheet("QLabel{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_currentPath.setText("")
        self.label_currentPath.setObjectName("label_currentPath")
        self.gridLayout.addWidget(self.label_currentPath, 2, 1, 1, 1)
        self.lineEdit_heatmap_out = QtWidgets.QLineEdit(self.widget_path_3)
        self.lineEdit_heatmap_out.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_heatmap_out.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_heatmap_out.setFont(font)
        self.lineEdit_heatmap_out.setStyleSheet("QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.lineEdit_heatmap_out.setText("")
        self.lineEdit_heatmap_out.setObjectName("lineEdit_heatmap_out")
        self.gridLayout.addWidget(self.lineEdit_heatmap_out, 10, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.widget_path_3)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar { \n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: rgb(20,20,20);\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"              stop: 0 rgba(232, 224, 234, 240), stop: 1 rgba(225, 229, 244,240));\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgba(230, 178, 194, 240), stop: 1 rgba(189, 202, 232, 240));\n"
"    border-radius: 10px;\n"
"    margin: 0.1px;  \n"
"    width: 1px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 11, 1, 1, 1)
        self.label_h5file = QtWidgets.QLabel(self.widget_path_3)
        self.label_h5file.setMinimumSize(QtCore.QSize(0, 25))
        self.label_h5file.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_h5file.setStyleSheet("QLabel{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_h5file.setText("")
        self.label_h5file.setObjectName("label_h5file")
        self.gridLayout.addWidget(self.label_h5file, 1, 1, 1, 1)
        self.lineEdit_video_out = QtWidgets.QLineEdit(self.widget_path_3)
        self.lineEdit_video_out.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_video_out.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_video_out.setFont(font)
        self.lineEdit_video_out.setStyleSheet("QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.lineEdit_video_out.setText("")
        self.lineEdit_video_out.setObjectName("lineEdit_video_out")
        self.gridLayout.addWidget(self.lineEdit_video_out, 8, 1, 1, 1)
        self.lineEdit_pic_out = QtWidgets.QLineEdit(self.widget_path_3)
        self.lineEdit_pic_out.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_pic_out.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_pic_out.setFont(font)
        self.lineEdit_pic_out.setStyleSheet("QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"    color: #333333;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.lineEdit_pic_out.setText("")
        self.lineEdit_pic_out.setObjectName("lineEdit_pic_out")
        self.gridLayout.addWidget(self.lineEdit_pic_out, 7, 1, 1, 1)
        self.title_bar = QtWidgets.QWidget(self.centralwidget)
        self.title_bar.setGeometry(QtCore.QRect(0, 0, 1181, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_bar.sizePolicy().hasHeightForWidth())
        self.title_bar.setSizePolicy(sizePolicy)
        self.title_bar.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-radius: 15px;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                  stop: 0 rgb(225, 182, 196), stop: 1 rgb(181, 205, 238));\n"
"")
        self.title_bar.setObjectName("title_bar")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.hboxlayout.setContentsMargins(15, 0, 15, 0)
        self.hboxlayout.setSpacing(15)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_title = QtWidgets.QLabel(self.title_bar)
        self.label_title.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"    background-color: rgba(200 ,200, 200,0);\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label_title.setObjectName("label_title")
        self.hboxlayout.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.button_min = QtWidgets.QPushButton(self.title_bar)
        self.button_min.setMinimumSize(QtCore.QSize(16, 16))
        self.button_min.setMaximumSize(QtCore.QSize(16, 16))
        self.button_min.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 190, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(0, 170, 255);\n"
"}")
        self.button_min.setText("")
        self.button_min.setObjectName("button_min")
        self.hboxlayout.addWidget(self.button_min)
        self.button_exit_1 = QtWidgets.QPushButton(self.title_bar)
        self.button_exit_1.setMinimumSize(QtCore.QSize(16, 16))
        self.button_exit_1.setMaximumSize(QtCore.QSize(16, 16))
        self.button_exit_1.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 60, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 170, 255);\n"
"}")
        self.button_exit_1.setText("")
        self.button_exit_1.setObjectName("button_exit_1")
        self.hboxlayout.addWidget(self.button_exit_1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_pic.setText(_translate("MainWindow", "单图模式"))
        self.button_files.setText(_translate("MainWindow", "多图模式"))
        self.button_heatmap.setText(_translate("MainWindow", "热力图模式"))
        self.button_video.setText(_translate("MainWindow", "视频模式"))
        self.button_realtime.setText(_translate("MainWindow", "实时检测模式"))
        self.button_select_file.setText(_translate("MainWindow", "选择待处理文件"))
        self.button_handle.setText(_translate("MainWindow", "开始检测"))
        self.button_stop.setText(_translate("MainWindow", "停止检测/播放"))
        self.button_confirm.setText(_translate("MainWindow", "保存输出路径"))
        self.button_display_result.setText(_translate("MainWindow", "选择图片显示"))
        self.button_display_result_2.setText(_translate("MainWindow", "选择视频播放"))
        self.button_about.setText(_translate("MainWindow", "关于"))
        self.button_exit_2.setText(_translate("MainWindow", "退出"))
        self.label_message_title.setText(_translate("MainWindow", "系统通知在这里!"))
        self.label_display_title.setText(_translate("MainWindow", "显示窗口"))
        self.label_display_path_2.setText(_translate("MainWindow", "文件路径："))
        self.label_01.setText(_translate("MainWindow", "模式："))
        self.label_06.setText(_translate("MainWindow", "输出的视频路径："))
        self.label_02.setText(_translate("MainWindow", "权重文件："))
        self.label_03.setText(_translate("MainWindow", "当前选中的文件："))
        self.label_07.setText(_translate("MainWindow", "输出的文件夹路径："))
        self.label_05.setText(_translate("MainWindow", "输出的图片路径："))
        self.label_08.setText(_translate("MainWindow", "输出的热力图路径："))
        self.label_04.setText(_translate("MainWindow", "处理进度："))
        self.label_title.setText(_translate("MainWindow", "交通标识检测助手v1.0b"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
